#!/bin/bash

# Aliases for git commands

alias gc='git clone'
alias ga='git add .'
alias gcm='git commit -m'
alias gp='git push'
alias gpl='git pull'

alias glogp='git log --pretty=format:"%h %s" --graph'