#!/bin/bash

# Aliases for git commands

alias gc='git clone'
alias ga='git add .'
alias gcm='git commit -m'
alias gp='git push'
alias gpl='git pull'
alias gpu='git push --set-upstream origin'

alias glogp='git log --pretty=format:"%h %s" --graph'