#!/bin/bash
# Aliases for Python and packages

# Virtualenv
alias vact="./env/Scripts/activate"

#pipenv
alias ps="pipenv shell"
alias pi="pipenv install"

# Django
alias rs="python manage.py runserver"
alias pmm="python manage.py makemigrations"
alias pm="python manage.py migrate"
alias pms="python manage.py shell"
