#!/usr/bin/env bash



# Window Controls
alias v="code ."



alias ..="cd ../.."

# frequent projects
alias dot="cd ~/.dotfiles/"
alias uni="cd $HOME/OneDrive/Desktop/Workshop/unicorn/"
alias qufro="cd $HOME/OneDrive/Desktop/Workshop/qufro/qufro_dev"


# Some important directories
alias work="cd $HOME/OneDrive/Desktop/Workshop"

