

# Update aliases for bash
source $HOME/.dotfiles/bash/aliases

# Update git aliases
source $HOME/.dotfiles/git/aliases

# Update python aliases
source $HOME/.dotfiles/python/aliases

# Update terraform aliases
source $HOME/.dotfiles/terraform/aliases

# Add bootstrap cli to bashrc so dev can run the commands anywhere. 
# This is a bit of a dangerous move 

export PATH=~/.dotfiles/installer/bootstrap:$PATH