#!/usr/bin/env python

# bootstrap cli tool that allows you to control scripts for your dotfiles

import os, sys

if __name__=="__main__":

    cmd_length = len(sys.argv)

    def run_linker():
        os.system("./linker")
        print("Symlink file successfully ran!")

    def run_bash():
        os.system("./bashrc_update")
        print("Source bashrc success!")

    # Show a cool meny
    if(len(sys.argv) == 1):
        os.system("cat menu.txt")

    elif(len(sys.argv) == 2):
        # Update symlinks
        if(sys.argv[1] == "link"):
            run_linker()
        # Source bashrc
        if(sys.argv[1] == "bash"):
            run_bash()

        # Update symlinks & source bashrc
        if(sys.argv[1] == 'update'):
            run_linker()
            run_bash()
