#!/usr/bin/env python


# bootstrap is a cli tool that allows you to control scripts for your dotfiles

import os, sys

if __name__=="__main__":

    cmd_length = len(sys.argv)

    # Functions runs the symlink script
    def run_linker():
        os.system("sh linker.sh")
        print("Symlink file successfully ran!")

    # updates the bashrc
    def run_bash():
        os.system("sh bashrc_update.sh")
        print("Source bashrc success!")

    # Show a cool menu
    if(len(sys.argv) == 1):
        os.system("cat menu.txt")

    elif(len(sys.argv) == 2):
        # Update symlinks
        if(sys.argv[1] == "link"):
            run_linker()
        # Source bashrc
        if(sys.argv[1] == "bash"):
            run_bash()

        # Update symlinks & source bashrc
        if(sys.argv[1] == 'update'):
            run_linker()
            run_bash()
